#pragma once

// Standard
#include <algorithm>
#include <iterator>
#include <set>
#include <sstream>
#include <string>
#include <vector>

// Windows
#define WIN32_LEAN_AND_MEAN
#define NOWINSTYLES
#define NOMENUS
#define NOSYSCOMMANDS
#define NORASTEROPS
#define NOATOM
#define NOCLIPBOARD
#define NOCOLOR
#define NODRAWTEXT
#define NOKERNEL
#define NOMB
#define NOMEMMGR
#define NOMETAFILE
#define NOMINMAX
#define NOOPENFILE
#define NOSCROLL
#define NOSERVICE
#define NOSOUND
#define NOWH
#define NOCOMM
#define NOKANJI
#define NOHELP
#define NOPROFILER
#define NODEFERWINDOWPOS
#define NOMCX
#include <windows.h>
#include <d3d9.h>
#include <d3dx9tex.h>
#include <DbgHelp.h>
#include <shellapi.h>
#include <ShlObj.h>
#include <Shlwapi.h>
#include <strsafe.h>
#include <WinInet.h>
#include <WinSock2.h>

// Third-party
#include <imgui.h>
#define IMGUI_DEFINE_MATH_OPERATORS
#include <imgui_internal.h>
