image: Visual Studio 2017
version: '{build}'
skip_branch_with_pr: true
skip_commits:
  message: /\[(ci skip|skip ci|docs)\]/

configuration: Release
platform:
  - x86
  - x64

cache:
  - packages -> **\packages.config

install:
  - git submodule update --init --recursive

before_build:
  - nuget restore
  - msbuild /t:loader:ExportVersion /p:Configuration=Release /p:ExportFile=../../.version /v:m
  - ps: Update-AppveyorBuild -Version "$(Get-Content .version)"

build:
  project: GW2 Addon Loader.sln
  parallel: true
  verbosity: minimal

after_build:
  - 7z a "GuildWars2AddonLoader_%APPVEYOR_BUILD_VERSION%_%PLATFORM%.zip" -r "%APPVEYOR_BUILD_FOLDER%\bin\%PLATFORM%\%CONFIGURATION%\*.dll"

artifacts:
  - path: GuildWars2AddonLoader_$(appveyor_build_version)_$(platform).zip
    name: GuildWars2AddonLoader_$(appveyor_build_version)_$(platform)

deploy:
  provider: GitHub
  description: "New release: $(appveyor_build_version)"
  auth_token:
    secure: /93cJH0TEPlM829Tak7dyn/tHJDBR3dxPtU5gQdU3kbTYlSq+FELMLsxHTcuhJ2D
  artifact: GuildWars2AddonLoader_$(appveyor_build_version)_$(platform).zip
  draft: true
  on:
    appveyor_repo_tag: true
