// Since this is not autogenerated, and we don't want to do this manually for 200+ icons,
// we just add one whenever we need it.
#pragma once

#define ICON_OC_HEART u8"\u2665"
#define ICON_OC_LOGO_GITHUB u8"\uf092"
#define ICON_OC_MARK_GITHUB u8"\uf00a"
