# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guild Wars 2 Add-on Loader
description: >-
  Guild Wars 2 Add-on Loader is an unofficial add-on for Guild Wars 2.
  It acts as a master add-on that makes it easy to manage your
  Guild Wars 2 add-ons without the need to manage the files manually.
url: "https://archomeda.github.io"
baseurl: "/gw2-addon-loader"
permalink: pretty

timezone: Europe/Amsterdam
date_format: '%A %-d %B %Y'

collections:
  posts:
    permalink: /updates/:year/:month/:title/
    output: true

repository: archomeda/gw2-addon-loader

twitter:
  username: archomeda

reddit:
  username: archomeda

feed:
  path: feed.xml

additional_navlinks:
  - url: /updates/
    weight: 0
    navigation:
      visible: true
      title: Archived updates

paginate: 5
paginate_path: /updates/page-:num

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
